version: '3.8'

services:

  # db:
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres

  backend:
    build: ./backend
    command: sh -c "cd .. && make run"
    env_file: ./backend/.env
    restart: always
    # depends_on:
    #     - db
    # links:
    #   - db:db
    volumes:
      - "./backend/app:/app"
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  # postgres_data:
  static_volume:
  media_volume: